In [349]:
import gymnasium as gym
import math
import random
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count
import numpy as np
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [350]:
gym.__version__

'0.29.1'

In [351]:
env = gym.make('CartPole-v1')
n_state = env.observation_space.shape[0]
n_action = env.action_space.n


In [357]:
state, info = env.reset()
state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)
weight = torch.rand(n_state, n_action)
total_reward = 0
terminated = False
truncated = False

In [355]:
def run_episode(env, weight):
    state, info = env.reset()
    grads = []
    total_reward = 0
    terminated = False
    truncated = False
    while not (terminated or truncated):
       state = torch.tensor(state, dtype=torch.float32).unsqueeze(0)
       z= torch.matmul(state, weight)
       probs=torch.nn.Softmax()(z)
       action = int(torch.bernoulli(probs[1]).item())
       d_softmax = torch.diag(probs) - probs.view(-1, 1) * probs
       d_log = d_softmax[action] / probs[action]
       grad = state.view(-1, 1) * d_log
       grads.append(grad)
       state, reward, terminated, truncated, _ = env.step(action)
       total_reward += reward 
       if (terminated or truncated): 
          break
       return total_reward, grads
       

In [358]:
n_episode = 1000
weight = torch.rand(n_state, n_action)
total_rewards = []
learning_rate = 0.001

In [359]:
for episode in range(n_episode):
    total_reward, gradients = run_episode(env, weight)
    print('Эпизод {}: {}'.format(episode + 1, total_reward))
    for i, gradient in enumerate(gradients):
        weight += learning_rate * gradient * (total_reward - i)
    total_rewards.append(total_reward)

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [363]:

z= torch.matmul(state, weight)
probs = torch.nn.Softmax()(z)
print("probs=\n",probs)

action = int(torch.bernoulli(probs[0,0]).item()) 
#action = int(torch.bernoulli(probs[1]).item()) - если сделать как в нижке, то падает
print("action:",action)

d_softmax = torch.diag(probs) - probs.view(-1, 1) * probs
d_log = d_softmax[action] / probs[action]

print("torch.diag(probs):\n", torch.diag(probs))
print("d_softmax=\n", d_softmax)
print("probs.view(-1, 1)=\n", probs.view(-1, 1))
print("probs.view(-1, 1) * probs=\n", probs.view(-1, 1) * probs)
print("d_log=\n", d_log)






probs=
 tensor([[0.5017, 0.4983]])
action: 0
torch.diag(probs):
 tensor([0.5017])
d_softmax=
 tensor([[0.2500, 0.2517],
        [0.2517, 0.2533]])
probs.view(-1, 1)=
 tensor([[0.5017],
        [0.4983]])
probs.view(-1, 1) * probs=
 tensor([[0.2517, 0.2500],
        [0.2500, 0.2483]])
d_log=
 tensor([0.4983, 0.5050])


In [364]:
probs=torch.nn.Softmax()(z)
print('z=',z)
print('probs=',probs)


z= tensor([[0.0077, 0.0010]])
probs= tensor([[0.5017, 0.4983]])


In [87]:
probs[0]

tensor([0.5063, 0.4937])

In [160]:
#torch.bernoulli(probs[1]).item()
probs

tensor([[0.5063, 0.4937]])

In [70]:
W=torch.tensor([[2,1], 
                [3,0],
                [4,2],
                [1,1]])
S= torch.tensor([[3,2,1,2]])

In [46]:
print("W=",W)
print("S=",S)

W= tensor([[2, 1],
        [3, 0],
        [4, 2],
        [1, 1]])
S= tensor([[3, 2, 1, 2]])


In [47]:
torch.matmul(S,W)

tensor([[18,  7]])